version: "3.9"

services:
  db:
    image: postgis/postgis:14-3.2
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    env_file: dev.env
    ports:
      - "5432:5432"
  web:
    build:
      context: ./
      dockerfile: dockerfiles/dev.Dockerfile
    volumes:
      - .:/code
    ports:
      - "8002:8000"
    env_file: dev.env
    depends_on:
      - db
  redis:
    image: redis:alpine
  celery:
    restart: always
    build:
      context: ./
      dockerfile: dockerfiles/celery.dev.Dockerfile
    command: celery -A backend worker -l info
    volumes:
      - ./:/code
    env_file: dev.env
    depends_on:
      - redis
      - db