# Generated by Django 3.2.10 on 2023-07-09 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('general_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generaluser',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.district'),
        ),
        migrations.AddField(
            model_name='generaluser',
            name='division',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.division'),
        ),
        migrations.AddField(
            model_name='generaluser',
            name='union',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.union'),
        ),
        migrations.AddField(
            model_name='generaluser',
            name='upazila',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.upazila'),
        ),
    ]
