# Generated by Django 3.2.10 on 2024-01-12 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='post_id',
            field=models.IntegerField(null=True),
        ),
    ]
