# Generated by Django 3.2.10 on 2024-01-12 13:56

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blood_banks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodbank',
            name='location_point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
