# Generated by Django 3.2.10 on 2024-01-12 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_banks', '0002_bloodbank_location_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodbank',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bloodbank',
            name='lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
